apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: istio-example-server
  namespace: default
spec:
  selector:
    matchLabels:
      app: istio-server-example
  jwtRules:
  - issuer: "testing@secure.istio.io"
    jwksUri: "https://raw.githubusercontent.com/istio/istio/release-1.8/security/tools/jwt/samples/jwks.json"

---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: istio-example-server
  namespace: default
spec:
  selector:
    matchLabels:
      app: istio-server-example
  action: ALLOW
  rules:
  - from:
    - source:
        requestPrincipals: ["*"]
