---
apiVersion: v1
kind: Service
metadata:
  name:  istio-front-example
spec:
  type: ClusterIP
  ports:
  - port: 80
    name: http
    targetPort: 80
  selector:
    app:  istio-front-example
---
# Source: hello-kubernetes/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: istio-front-example
  labels:
    app: istio-front-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: istio-front-example
  template:
    metadata:
      labels:
        app: istio-front-example
    spec:
      containers:
      - name: istio-front-example
        image: lukascaska/istio-example-front:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
