---
apiVersion: v1
kind: Service
metadata:
  name:  istio-server-example-legacy
spec:
  type: ClusterIP
  ports:
  - port: 3000
    name: http
    targetPort: 3000
  selector:
    app:  istio-server-example-legacy
---
# Source: hello-kubernetes/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: istio-server-example-legacy
  labels:
    app: istio-server-example-legacy
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: istio-server-example-legacy
      version: v2
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: istio-server-example-legacy
        version: v2
    spec:
      containers:
      - name: istio-server-example
        image: lukascaska/istio-example-server:v2
        ports:
        - containerPort: 3000
